data:
  waveform_dataset_path: Dingo/data/waveform_dataset.hdf5
  extrinsic_prior:
    luminosity_distance_A: bilby.gw.prior.UniformSourceFrame(minimum=20000.0, maximum=150000.0,
      name='luminosity_distance_A')
    dec_A: bilby.core.prior.Cosine(name='dec_A')
    ra_A: bilby.core.prior.Uniform(minimum=0.0, maximum=6.283185307179586, name='ra_A')
    theta_jn_A: bilby.core.prior.Sine(name='theta_jn_A')
    psi_A: bilby.core.prior.Uniform(minimum=0.0, maximum=3.141592653589793, name='psi_A')
    phase_A: bilby.core.prior.Uniform(minimum=0.0, maximum=6.283185307179586, name='phase_A')
    geocent_time_A: bilby.core.prior.Uniform(minimum=20.0, maximum=50.0, name='geocent_time_A')
    luminosity_distance_B: bilby.gw.prior.UniformSourceFrame(minimum=20000.0, maximum=150000.0,
      name='luminosity_distance_B')
    dec_B: bilby.core.prior.Cosine(name='dec_B')
    ra_B: bilby.core.prior.Uniform(minimum=0.0, maximum=6.283185307179586, name='ra_B')
    theta_jn_B: bilby.core.prior.Sine(name='theta_jn_B')
    psi_B: bilby.core.prior.Uniform(minimum=0.0, maximum=3.141592653589793, name='psi_B')
    phase_B: bilby.core.prior.Uniform(minimum=0.0, maximum=6.283185307179586, name='phase_B')
    delta_t_AB: bilby.core.prior.Uniform(minimum=0.0001, maximum=10.0, name='delta_t_AB')
  train_fraction: 0.95
  domain_update:
    f_min: 10.0
    f_max: 1024.0
  detectors:
  - H1
  - L1
  inference_parameters:
  - mass_1_A
  - mass_2_A
  - a_1_A
  - a_2_A
  - tilt_1_A
  - tilt_2_A
  - phi_12_A
  - phi_jl_A
  - luminosity_distance_A
  - dec_A
  - ra_A
  - theta_jn_A
  - psi_A
  - phase_A
  - geocent_time_A
  - mass_1_B
  - mass_2_B
  - a_1_B
  - a_2_B
  - tilt_1_B
  - tilt_2_B
  - phi_12_B
  - phi_jl_B
  - luminosity_distance_B
  - dec_B
  - ra_B
  - theta_jn_B
  - psi_B
  - phase_B
  - delta_t_AB
  context_parameters: []
  ref_time: 0.0
model:
  posterior_model_type: copula_normalizing_flow
  posterior_kwargs:
    input_dim: 30
    context_dim: 128
    block_dims:
    - 15
    - 15
    flow_1:
      num_flow_steps: 5
      base_transform_kwargs:
        hidden_dim: 128
        num_transform_blocks: 5
        activation: elu
        dropout_probability: 0.0
        batch_norm: true
        num_bins: 8
        base_transform_type: rq-coupling
    flow_2:
      num_flow_steps: 5
      base_transform_kwargs:
        hidden_dim: 128
        num_transform_blocks: 5
        activation: elu
        dropout_probability: 0.0
        batch_norm: true
        num_bins: 8
        base_transform_type: rq-coupling
    CopulaKwargs:
      p: 1
      hidden_dims:
      - 64
      - 64
      activation: elu
      dropout: 0.0
      batch_norm: false
  embedding_kwargs:
    output_dim: 128
    hidden_dims:
    - 128
    activation: elu
    dropout: 0.0
    batch_norm: true
    svd:
      num_training_samples: 400
      num_validation_samples: 50
      size: 64
training:
  stage_0:
    epochs: 300
    asd_dataset_path: Dingo/data/asd_dataset.hdf5
    freeze_rb_layer: true
    optimizer:
      type: adam
      lr: 5.0e-05
    scheduler:
      type: cosine
      T_max: 300
    batch_size: 4096
  stage_1:
    epochs: 150
    asd_dataset_path: Dingo/data/asd_dataset.hdf5
    freeze_rb_layer: false
    optimizer:
      type: adam
      lr: 1.0e-05
    scheduler:
      type: cosine
      T_max: 150
    batch_size: 4096
local:
  device: cpu
  num_workers: 4
  runtime_limits:
    max_time_per_run: 3600000
    max_epochs_per_run: 500
  checkpoint_epochs: 10
  leave_waveforms_on_disk: true
