data:
  waveform_dataset_path: Dingo/data/waveform_dataset.hdf5
  extrinsic_prior:
    luminosity_distance_A: bilby.core.prior.DeltaFunction(peak=50000.0, name='luminosity_distance_A')
    dec_A: bilby.core.prior.DeltaFunction(peak=0.0, name='dec_A')
    ra_A: bilby.core.prior.DeltaFunction(peak=0.0, name='ra_A')
    theta_jn_A: bilby.core.prior.DeltaFunction(peak=1.0, name='theta_jn_A')
    psi_A: bilby.core.prior.DeltaFunction(peak=0.0, name='psi_A')
    phase_A: bilby.core.prior.DeltaFunction(peak=0.0, name='phase_A')
    geocent_time_A: bilby.core.prior.DeltaFunction(peak=30.0, name='geocent_time_A')
    luminosity_distance_B: bilby.core.prior.DeltaFunction(peak=60000.0, name='luminosity_distance_B')
    dec_B: bilby.core.prior.DeltaFunction(peak=0.3, name='dec_B')
    ra_B: bilby.core.prior.DeltaFunction(peak=1.0, name='ra_B')
    theta_jn_B: bilby.core.prior.DeltaFunction(peak=1.2, name='theta_jn_B')
    psi_B: bilby.core.prior.DeltaFunction(peak=0.5, name='psi_B')
    phase_B: bilby.core.prior.DeltaFunction(peak=1.0, name='phase_B')
    delta_t_AB: bilby.core.prior.DeltaFunction(peak=1.0, name='delta_t_AB')
  domain_update:
    f_min: 10.0
    f_max: 1024.0
  detectors:
  - H1
  - L1
  inference_parameters:
  - chirp_mass_A
  - mass_ratio_A
  - chirp_mass_B
  - mass_ratio_B
  context_parameters: []
  ref_time: 0.0
  train_fraction: 0.95
model:
  posterior_model_type: copula_normalizing_flow
  posterior_kwargs:
    context_dim: 128
    block_dims:
    - 2
    - 2
    flows:
      flow_1:
        num_flow_steps: 30
        base_transform_kwargs:
          hidden_dim: 1024
          num_transform_blocks: 5
          activation: elu
          dropout_probability: 0.0
          batch_norm: true
          num_bins: 8
          base_transform_type: rq-coupling
      flow_2:
        num_flow_steps: 30
        base_transform_kwargs:
          hidden_dim: 1024
          num_transform_blocks: 5
          activation: elu
          dropout_probability: 0.0
          batch_norm: true
          num_bins: 8
          base_transform_type: rq-coupling
    CopulaKwargs:
      P: 3
      hidden_dims:
      - 64
      - 64
      activation: elu
      dropout: 0.0
      batch_norm: false
  embedding_kwargs:
    output_dim: 128
    hidden_dims:
    - 1024
    - 1024
    - 1024
    - 1024
    - 1024
    - 1024
    - 512
    - 512
    - 512
    - 512
    - 512
    - 512
    - 256
    - 256
    - 256
    - 256
    - 256
    - 256
    - 128
    - 128
    - 128
    - 128
    - 128
    - 128
    activation: elu
    dropout: 0.0
    batch_norm: true
    svd:
      num_training_samples: 500
      num_validation_samples: 100
      size: 600
training:
  stage_0:
    epochs: 100
    asd_dataset_path: Dingo/data/asd_dataset.hdf5
    freeze_rb_layer: true
    optimizer:
      type: adam
      lr: 0.0005
    scheduler:
      type: cosine
      T_max: 500
    batch_size: 4096
  stage_1:
    epochs: 500
    asd_dataset_path: Dingo/data/asd_dataset.hdf5
    freeze_rb_layer: false
    optimizer:
      type: adam
      lr: 2.0e-05
    scheduler:
      type: cosine
      T_max: 500
    batch_size: 4096
    early_stopping:
      patience: 10
      delta: 0.0
      metric: validation
local:
  device: cpu
  num_workers: 16
  runtime_limits:
    max_time_per_run: 36000000
    max_epochs_per_run: 1000
  checkpoint_epochs: 100
  leave_waveforms_on_disk: true
  wandb:
    project: dingo-copula
    group: gaussian-mean-debug
